# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-04 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FillUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('odometer', models.DecimalField(decimal_places=2, max_digits=8)),
                ('gallons', models.DecimalField(decimal_places=3, max_digits=6)),
                ('cpg', models.DecimalField(decimal_places=3, max_digits=5)),
                ('fuel_type', models.CharField(max_length=200)),
            ],
        ),
    ]
